version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/edulastic-poc
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: /home/ec2-user/edulastic-poc/scripts/npm-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: /home/ec2-user/edulastic-poc/scripts/npm-start.sh
      runas: ec2-user
      timeout: 60
