const SMART_FILTERS = {
  ENTIRE_LIBRARY: "ENTIRE_LIBRARY",
  AUTHORED_BY_ME: "AUTHORED_BY_ME",
  SHARED_WITH_ME: "SHARED_WITH_ME",
  CO_AUTHOR: "CO_AUTHOR",
  FAVORITES: "FAVORITES"
};

module.exports = { SMART_FILTERS };
