export const teacherSide = {
  NOT_OPEN: "NOT OPEN",
  IN_PROGRESS: "IN PROGRESS",
  IN_GRADING: "IN GRADING",
  NOT_GRADED: "NOT GRADED",
  GRADES_HELD: "GRADES HELD",
  DONE: "DONE",
  REDIRECTED: "REDIRECTED"
};

export const studentSide = {
  NOT_STARTED: "NOT STARTED",
  IN_PROGRESS: "IN PROGRESS",
  SUBMITTED: "SUBMITTED",
  NOT_GRADED: "NOT GRADED",
  GRADES_HELD: "GRADES HELD",
  GRADED: "GRADED"
};
