export const methodName = {
  equivSymbolic: "Symbolically Equivalent",
  equivLiteral: "Literally Equivalent",
  equivValue: "Equivalent value",
  isSimplified: "Check if expression is simplified",
  isFactorised: "Check if expression is factored",
  isExpanded: "Check if expression is expanded",
  isRationalized: "Check if rationalized",
  stringMatch: "Plain Text",
  equivSyntax: "Equivalent Syntax",
  setEvaluation: "Set Evaluation",
  isTrue: "Check if true"
};

export const optionsAttribute = {
  isSimpleFraction: "answer-is-simple-fraction",
  isMixedFraction: "answer-is-mixed-fraction",
  isExpanded: "answer-is-expanded",
  isFactorised: "answer-is-factorised",
  isSimplified: "answer-is-simplified",
  ignoreCoefficientOfOne: "answer-ignore-coefficient-of-one",
  ignoreTrailingZeros: "answer-ignore-trailing-zeros",
  ignoreLeadingAndTrailingSpaces: "answer-ignore-leading-and-trailing-spaces",
  isDecimal: "answer-is-decimal",
  ignoreOrder: "answer-ignore-order",
  allowEulersNumber: "answer-allow-eulers-number",
  compareSides: "answer-compare-sides",
  treatMultipleSpacesAsOne: "answer-treat-multiple-spaces-as-one",
  inverseResult: "answer-inverse-result",
  tolerance: "answer-allow-tolerance",
  significantDecimalPlaces: "answer-allow-significant-decimal-places",
  setThousandsSeparator: "answer-allow-thousand-separator",
  setDecimalSeparator: "answer-allow-decimal-separator",
  allowedUnits: "answer-allowed-units",
  allowNumericOnly: "answer-allow-numeric-only",
  allowedVariables: "answer-allowed-variables",
  interpretAsSet: "answer-set-evaluation",
  setListTypeResponse: "answer-list-evaluation",
  isRationalized: "answer-rationalized"
};

export const maths = {
  enterQuestion: "Enter your question",
  bold: "Bold",
  italic: "Italic",
  underline: "Underline",
  clearFormatting: "Clear formatting",
  bulletList: "Bullet list",
  numberedList: "Numbered list",
  superscript: "Superscript",
  subscript: "Subscript",
  composeQuestion: "Question",
  textFormattingOptions: "Text formatting options",
  add: "Add",
  correctAnswers: "Correct Answer",
  alternateAnswers: "Alternate Answer",
  dot: "Dot",
  dropdown: "Dropdown",
  keypad: "Keypad",
  comma: "Comma",
  space: "Space",
  decimal: "Decimal",
  simpleFraction: "Check for simple fraction",
  mixedFraction: "Check for mixed fraction",
  exponent: "Exponent",
  standardForm: "Standard Form",
  slopeInterceptForm: "Slope Intercept Form",
  integer: "Integer",
  scientific: "Scientific",
  variable: "Variable",
  number: "Number",
  pointSlopeForm: "Point SlopeForm",
  method: "Method",
  field: "Field",
  value: "Value",
  ariaLabel: "ARIA label",
  allowedUnits: "Must use these units",
  ignoreLeadingAndTrailingSpaces: "Ignore leading and trailing spaces",
  treatMultipleSpacesAsOne: "Treat extra spaces as one",
  rule: "Rule",
  argument: "Argument",
  ignoreOrder: "Ignore order",
  allowNumericOnly: "Restrict to numeric input",
  allowedVariables: "Restrict variables used to",
  showDropdown: "Show units in",
  customizeunits: "Customize Units",
  allowInterval: "Allow interval",
  ignoreTrailingZeros: "Ignore trailing zeros in a decimal",
  ignoreCoefficientOfOne: 'Ignore a "1" in front of a variable',
  inverseResult: "Inverse result",
  significantDecimalPlaces: "Significant decimal places",
  ignoreAlphabeticCharacters: "Ignore alphabet characters",
  compareSides: "Compare both sides of the in/equality",
  treatEAsEulersNumber: "Interpret 'e' as Euler's number",
  tolerance: "Allow tolerance",
  allowDecimalMarks: "Allow decimal marks",
  decimalSeparator: "Decimal separator",
  addNewMethod: "Add new method",
  exactMatch: "Exact match",
  partialMatch: "Partial Match",
  template: "Template",
  allowThousandsSeparator: "Allow specifying thousands separator",
  composequestion: "Question",
  compareUsing: "Compare Using",
  expectedAnswer: "Expected Answer",
  addComparison: "Add Comparison",
  chainAnotherEvaluationRule: "Chain another evaluation rule",
  equivSymbolic: "Symbolically Equivalent",
  equivLiteral: "Literally Equivalent",
  equivValue: "Equivalent value",
  isSimplified: "Check if expression is simplified",
  isFactorised: "Check if expression is factored",
  isExpanded: "Check if expression is expanded",
  isTrue: "Check if true",
  stringMatch: "Plain Text",
  equivSyntax: "Equivalent Syntax",
  isDecimal: "Check if number is a decimal",
  isSimpleFraction: "Check for simple fraction",
  isMixedFraction: "Check for mixed fraction",
  isExponent: "Check if variable is an exponent",
  isStandardForm: "Check if equation is in standard form",
  isSlopeInterceptForm: "Check if equation is in slope intercept form",
  isPointSlopeForm: "Check if equation is in point slope form",
  choicesfordropdown: "Choices for Text Dropdown",
  additionalOptions: "Additional Options",
  setThousandsSeparator: "Set Thousands Separator",
  setEvaluation: "Set Evaluation",
  interpretAsSet: "Interpret Response as Set",
  isRationalized: "Check if rationalized",
  setListTypeResponse: "Interpret Response as List",
  setDecimalSeparator: "Set Decimal Separator"
};

export const rules = {
  DECIMAL: "isDecimal",
  SIMPLE_FRACTION: "isSimpleFraction",
  MIXED_FRACTION: "isMixedFraction",
  EXPONENT: "isExponent",
  STANDARD_FORM: "isStandardForm",
  SLOPE_INTERCEPT_FORM: "isSlopeInterceptForm",
  POINT_SLOPE_FORM: "isPointSlopeForm",
  NUMBER: "numberType",
  INTEGER: "integerType",
  SCIENTIFIC: "scientificType",
  VARIABLE: "variableType"
};

export const fields = {
  INTEGER: "integerType",
  REAL: "realType",
  COMPLEX: "complexType"
};

export const methodsKey = {
  EQUIV_SYMBOLIC: "equivSymbolic",
  EQUIV_LITERAL: "equivLiteral",
  EQUIV_VALUE: "equivValue",
  IS_SIMPLIFIED: "isSimplified",
  IS_FACTORISED: "isFactorised",
  IS_EXPANDED: "isExpanded",
  IS_RATIONALIZED: "isRationalized",
  STRING_MATCH: "stringMatch",
  EQUIV_SYNTAX: "equivSyntax",
  SET_EVALUATION: "setEvaluation",
  CHECK_IF_TRUE: "isTrue"
};
