import edulasticDefaultLogo from './assets/logo.svg';

export const themes = {
  default: {
    logo: edulasticDefaultLogo,
    logoBorderBottomColor: '#d9d6d6',
    sidebarBgColor: '#fbfafc',
    sidebarTextColor: '#434b5d',
    helpButtonBgColor: '#ffffff',
    helpButtonBgHoverColor: '#1890ff',
    helpButtonSvgHoverColor: 'white',
    helpIconColor: '#1fe3a1',
    dropdownIconColor: 'white',
    userInfoButtonBgColor: '#1fe3a1',
    userInfoNameTextColor: '#057750',
    userInfoNameFontSize: '14px',
    userInfoRoleTextColor: 'white',
    userInfoRoleFontSize: '12px',
    userInfoDropdownBgColor: '#1fe3a1',
    userInfoDropdownItemBgColor: 'transparent',
    userInfoDropdownItemBgHoverColor: '#4fd08c',
    userInfoDropdownItemTextColor: 'white',
    userInfoDropdownItemTextHoverColor: 'white',
    userInfoDropdownItemFontSize: '14px',
    userInfoDropdownItemIconColor: '#425066',
    userInfoDropdownItemIconHoverColor: 'white',
    userInfoDropdownItemIconSize: '20px',
    menuContainerBgColor: 'transparent',
    menuItemBgColor: 'transparent',
    menuSelectedItemBgColor: 'transparent',
    menuItemLinkColor: '#4aac8b',
    menuSelectedItemLinkColor: '#4aac8b',
    menuItemLinkHoverColor: '#4aac8b',
    selectedMenuItemBorderLeft: 'rgb(74, 172, 139)',
    headerBgColor: '#0288d1',
    headerClassTitleColor: 'white',
    headerClassTitleFontSize: '13px',
    headerTitleTextColor: 'white',
    headerTitleFontSize: '22px',
    headerDropdownBgColor: 'white',
    headerDropdownTextColor: '#444444',
    headerDropdownFontSize: '14px'
  },
  crazyTheme: {
    logo: edulasticDefaultLogo,
    logoBorderBottomColor: 'red',
    sidebarBgColor: 'yellow',
    sidebarTextColor: 'red',
    helpButtonBgColor: 'red',
    helpButtonBgHoverColor: 'green',
    helpButtonSvgHoverColor: 'white',
    helpIconColor: 'orange',
    dropdownIconColor: 'lime',
    userInfoButtonBgColor: 'red',
    userInfoNameTextColor: 'yellow',
    userInfoNameFontSize: '14px',
    userInfoRoleTextColor: 'lime',
    userInfoRoleFontSize: '12px',
    userInfoDropdownBgColor: '#40407a',
    userInfoDropdownItemBgColor: '#34ace0',
    userInfoDropdownItemBgHoverColor: '#227093',
    userInfoDropdownItemTextColor: '#ffda79',
    userInfoDropdownItemTextHoverColor: 'red',
    userInfoDropdownItemFontSize: '14px',
    userInfoDropdownItemIconColor: '#40407a',
    userInfoDropdownItemIconHoverColor: 'yellow',
    userInfoDropdownItemIconSize: '20px',
    menuContainerBgColor: '#ffda79',
    menuItemBgColor: 'transparent',
    menuSelectedItemBgColor: 'green',
    menuItemLinkColor: 'green',
    menuSelectedItemLinkColor: 'yellow',
    menuItemLinkHoverColor: 'yellow',
    selectedMenuItemBorderLeft: 'rgb(74, 172, 139)',
    headerBgColor: '#0288d1',
    headerClassTitleColor: 'white',
    headerClassTitleFontSize: '13px',
    headerTitleTextColor: 'white',
    headerTitleFontSize: '22px',
    headerDropdownBgColor: 'yellow',
    headerDropdownTextColor: 'red',
    headerDropdownFontSize: '18px'
  }
};
