export const videoDatas = [
    {url:'http://techslides.com/demos/sample-videos/small.mp4'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/10q_1.mov', answers: 'C,A D,C,B,A,A C,B,A,D,C'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/10q_2.mov', answers: 'C,A D,C,B,A,A C,B,A,D,C'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/10q_3.mov', answers: 'C,A D,C,B,A,A C,B,A,D,C'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/10q_4.mov', answers: 'C,A B D,C,B D,A D,A C D,B,A,C D,C'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/14q_1.mov', answers: 'A D F,,,,D,,B,,,D,,,,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/14q_2.mov', answers: 'A D F,D,,A C,D,,B,,,D,A,B,B,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/14q_3.mov', answers: 'A D F,D,,A C,D,,B,,,D,A,B,B,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/14q_4.mov', answers: 'A D F,D,,A C,D,,B,,,D,A,B,B,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/14q_bl.mov', answers: ',,,,,,,,,,,,,'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/28q_1.mov', answers: ',A,,,B,,,,B,,,C,,,,,A,,,D,,,E,C,B,,,'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/28q_2.mov', answers: 'F,A,C,,B D,D,,A C D,B,D,A,A C,D,C,D,E,A,D,C,D,D,,E,C,B,,C,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/28q_3.mov', answers: 'F,A,C,,B D,D,,A C D,B,D,A,A C,D,C,D,E,A,D,C,D,D,,E,C,B,,C,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/28q_bl.mov', answers: ',,,,,,,,,,,,,,,,,,,,,,,,,,,'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/40q_1.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A,,C,,D,,C,,D,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/40q_2.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A,,C,,D,,C,,D,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/40q_3.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A,,C,,D,A D,C,D,D,A D'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/40q_4.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A,,C,,D,A D,C,D,D,A D'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/dc40_1.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/dc40_2.mov', answers: 'C,C,B,B,C,A,D,B,C,A B,C,C,B,C,D,C,B,A,C D,C D,D,C,D,B,C,D E,C,C,A,A,A'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/dc40_3.mov', answers: 'C,A B D,C,B D,A D,A C D,B,A,C D,C'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/sep29_big_qr_1.mov', answers: 'D F, C, C, , B, C, D, C, C, C, A, A, , B, D, A E, C, C, B, D, B D, A, B D E'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/sep29_big_qr_3.mov', answers: 'A D F, C, C, D, B, C, D, C, B C, C, A, A, , B, D, A E, C, C, B, D, B D, A, B D E'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/sep29_bigqr_2.mov', answers: 'A D F, C, C, D, B, C, D, C, B C, C, A, A, , B, D, A E, C, C, B, D, B D, A, B D E'},
    {url: 'https://s3.amazonaws.com/edureact-dev/bubble_sheet_webcam_test_videos/video/sep29_bigqr_5.mov', answers: 'A D F, C, C, D, B, C, D, C, B C, C, A, A, , B, D, A E, C, C, B, D, B D, A, B D E'},
];