export const studentInformation = {
  studentId: 'studentId',
  firstName: 'firstName',
  lastName: 'lastName',
  schoolName: ' schoolName',
  groupId: 'groupId',
  subject: 'subject',
  grades: '1',
  courseName: 'courseName',
  courseId: 'courseId',
  standardSet: 'standardSet',
  termId: 'termId',
  frlStatus: 'Yes',
  iepStatus: 'No',
  ellStatus: 'Yes',
  hispanicEthnicity: 'Yes',
}

export const tableData = [
  {
    totalQuestions: 0,
    assignmentId: '62fca80a92e57e0009aa8d00',
    groupId: '62daacbdffcb990009f78e2b',
    studentId: '61bc392ff6d9b7f1b6200626',
    maxScore: 5,
    reportKey: '62fca7e93d0413000aa70f08',
    score: 2.6667,
    testActivityId: '62fca80a92e57e0009aa8d01',
    testId: '62fca7e93d0413000aa70f08',
    totalTestItems: 3,
    assignmentDate: '1660725248288',
    testType: 'Class Assessment',
    title: 'Normal Test01',
    testName: 'Normal Test01',
    totalScore: 2.6667,
    totalMaxScore: 5,
    standardSet: 'Virginia Mathematics',
    subject: 'Mathematics',
    averageScore: 53.334,
    band: {
      color: '#EBDD54',
      threshold: 50,
      aboveStandard: 1,
      name: 'Basic',
    },
    assignmentDateFormatted: 'Aug 17, 2022',
    districtAvg: 53,
    groupAvg: 53,
    schoolAvg: 53,
    rawScore: '2.67 / 5',
  },
  {
    achievementLevel: 3,
    achievementLevelInfo: {
      color: '#fec571',
      id: 3,
      name: 'Standard Met',
      testTitle: 'Smarter Balanced Summative for Mathematics',
    },
    assignmentDate: 1652832000000,
    assignmentDateFormatted: 'May 18, 2022',
    assignmentId: '',
    claimsInfo: [
      { color: '#798cce', name: 'Concepts and Procedures', value: 596 },
      {
        color: '#a1c3ea',
        name: 'Problem Solving and Modeling/Data Analysis',
        value: 2970,
      },
      { color: '#f39300', name: 'Communicating Reasoning', value: 2220 },
    ],
    districtAvg: 2578,
    externalTestType: 'CAASPP',
    groupAvg: '-',
    groupId: '',
    maxScore: undefined,
    rawScore: '2612.00 / 0',
    reportKey: '',
    schoolAvg: 2601,
    score: 2612,
    standardSet: 'Math - Common Core',
    studentId: '61bc392ff6d9b7f1b6200626',
    subject: 'Mathematics',
    testActivityId: '',
    testId: 'Smarter Balanced Summative for Mathematics',
    testName: 'Smarter Balanced Summative for Mathematics',
    testType: 'External Assessment',
    title: 'Smarter Balanced Summative for Mathematics',
    totalMaxScore: 0,
    totalQuestions: 0,
    totalScore: 2612,
  },
]
