export { addEvaluationWatcherSaga as answerSaga } from './sharedDucks/AssignmentModule/ducks'
export { watcherSaga as skillReportSaga } from './SkillReport/ducks'
export { AssignmentSaga as studentAssignmentsSaga } from './Assignments'
export { authenticationSaga } from './Login'
export { testActivityReportSaga } from './TestAcitivityReport'
export { signupSaga } from './Signup'
export { studentManageClassSaga } from './ManageClass'
export { StudentPlaylistSaga } from './StudentPlaylist'
export { StudentSectionsSaga } from './SectionsStart'
