import edulasticDefaultLogo from './assets/logo.svg';

export const themes = {
  default: {
    logo: edulasticDefaultLogo,
    logoBorderBottomColor: '#d9d6d6',
    sidebarBgColor: '#fbfafc',
    sidebarTextColor: '#434b5d',
    helpButtonBgColor: '#ffffff',
    helpButtonBgHoverColor: '#1890ff',
    helpButtonFontSize: '14px',
    helpButtonTextColor: '#1fe3a1',
    helpButtonTextHoverColor: 'white',
    helpIconColor: '#1fe3a1',
    dropdownIconColor: 'white',
    userInfoButtonBgColor: '#1fe3a1',
    userInfoNameTextColor: '#057750',
    userInfoNameFontSize: '14px',
    userInfoRoleTextColor: 'white',
    userInfoRoleFontSize: '12px',
    userInfoDropdownBgColor: '#1fe3a1',
    userInfoDropdownItemBgColor: 'transparent',
    userInfoDropdownItemBgHoverColor: '#4fd08c',
    userInfoDropdownItemTextColor: 'white',
    userInfoDropdownItemTextHoverColor: 'white',
    userInfoDropdownItemFontSize: '14px',
    userInfoDropdownItemIconColor: '#425066',
    userInfoDropdownItemIconHoverColor: 'white',
    userInfoDropdownItemIconSize: '20px',
    menuContainerBgColor: 'transparent',
    menuItemBgColor: 'transparent',
    menuSelectedItemBgColor: 'transparent',
    menuItemLinkColor: '#434b5d',
    menuSelectedItemLinkColor: '#4aac8b',
    menuItemLinkHoverColor: '#1890ff',
    selectedMenuItemBorderLeft: 'rgb(74, 172, 139)',
    headerBgColor: '#0288d1',
    headerClassTitleColor: 'white',
    headerClassTitleFontSize: '13px',
    headerTitleTextColor: 'white',
    headerTitleFontSize: '22px',
    headerDropdownBgColor: 'white',
    headerDropdownTextColor: '#444444',
    headerDropdownFontSize: '14px',
    assignment: {
      cardContainerBgColor: 'white',
      cardTitleColor: '#12a6e8',
      cardTitleFontSize: '16px',
      cardTitleFontFamily: 'Open Sans',
      cardTimeIconType: 'clock-circle',
      cardTimeIconColor: '#ee1658',
      cardTimeTextFontSize: '13px',
      cardTimeTextColor: '#444444',
      cardSubmitLabelFontSize: '10px',
      cardSubmitedLabelBgColor: '#eacbff',
      cardSubmitedLabelTextColor: '#7d43a4',
      cardNotStartedLabelBgColor: '#cbeeff',
      cardNotStartedLabelTextColor: '#0083be',
      cardInProgressLabelBgColor: '#daeee7',
      cardInProgressLabelTextColor: '#4aacbb',
      cardMissedLabelBgColor: '#efefef',
      cardMissedLabelTextColor: '#878282',
      cardGradedLabelBgColor: '#fff1cb',
      cardGradedLabelTextColor: '#b56700',
      cardRetakeBtnFontSize: '11px',
      cardRetakeBtnBgColor: 'white',
      cardRetakeBtnBgHoverColor: '#12a6e8',
      cardRetakeBtnTextColor: '#00b0ff',
      cardRetakeBtnTextHoverColor: 'white',
      cardAttemptLinkTextColor: '#12a6e8',
      cardAttemptLinkFontSize: '12px',
      cardResponseBoxLabelsColor: '#434b5d',
      cardResponseBoxLabelsFontSize: '12px',
      cardAnswerAndScoreTextSize: '30px',
      cardAnswerAndScoreTextColor: '#434b5d',
      attemptsReviewRowBgColor: '#f8f8f8',
      attemptsReviewRowTextColor: '#9ca0a9',
      attemptsReviewRowFontSize: '12px',
      attemptsRowReviewLinkSize: '12px',
      attemptsRowReviewLinkColor: '#00b0ff'
    },
    headerFilters: {
      headerFilterTextSize: '10px',
      headerFilterTextColor: '#00b0ff',
      headerFilterBgColor: 'transparent',
      headerFilterBgBorderColor: '#00b0ff',
      headerFilterTextHoverColor: '#00b0ff',
      headerFilterBgHoverColor: 'white',
      headerFilterBgBorderHoverColor: '#00b0ff',
      headerSelectedFilterTextColor: 'white',
      headerSelectedFilterBgColor: '#00b0ff',
      headerSelectedFilterBgBorderColor: '#00b0ff'
    },
    breadcrumbs: {
      breadcrumbTextColor: '#00b0ff',
      breadcrumbTextSize: '10px',
      breadcrumbLinkColor: '#00b0ff'
    },
    reportList: {
      reportListTitleColor: '#12a6e8',
      reportListTitleTextSize: '16px',
      reportListBackButtonBgColor: 'transparent',
      reportListBackButtonBgBorderColor: '#00b0ff',
      reportListBackButtonTextColor: '#00b0ff',
      reportListBackButtonBgHoverColor: '#00b0ff',
      reportListBackButtonBgBorderHoverColor: 'white',
      reportListBackButtonTextHoverColor: 'white',
      reportListBackButtonTextSize: '0.7rem',
      reportListTotalScoreTextColor: '#434b5d',
      reportListTotalScoreTextSize: '1.5rem',
      reportListQuestionBorderColor: '#e61e54',
      reportListQuestionTextColor: '#444444',
      reportListQuestionTextSize: '14px',
      scoreBoxBorderBottomColor: '#434b5d',
      teacherFeedbarLabelColor: '#444444',
      teacherFeedbarLabelFontSize: '0.8rem',
      teacherFeedbarTextColor: '#878282',
      teacherFeedbarTextSize: '0.8rem',
      reportListAnswerLabelColor: '#444444',
      reportListAnswerLabelFontSize: '0.8rem'
    },
    skillReport: {
      skillReportTitleColor: '#4aac8b',
      skillReportTitleFontSize: '16px',
      RelationTitleColor: '#434b5d',
      RelationTitleFontSize: '14px',
      greenColor: '#1fe3a1',
      yellowColor: '#fdcc3b',
      redColor: '#ee1658',
      expandIconColor: '#4aac8b',
      collapseIconColor: '#4aac8b',
      gradeColumnTagBgColor: '#d7faee',
      gradeColumnTagColor: '#4aac8b',
      gradeColumnTagTextSize: '10px',
      tableHeaderBgColor: '#f5f9fe',
      tableHeaderTextColor: '#434b5d',
      tableHeaderHoverBgColor: '#f2f2f2',
      tableHeaderHoverTextColor: '#434b5d',
      tableHeaderTextSize: '13px',
      tableDataBgColor: 'white',
      tableDataBgBorderColor: '#f8f8f8',
      tableDataTextColor: 'rgba(0, 0, 0, 0.65)',
      tableDataFontSize: '13px'
    },
    noData: {
      NoDataBgColor: '#efefef',
      NoDataBgBorderColor: '#e9e9e9',
      NoDataArchiveTextColor: '#434b5d',
      NoDataArchiveTextSize: '17px',
      NoDataArchiveSubTextColor: '#434b5d',
      NoDataArchiveSubTextSize: '15px'
    },
    classCard: {
      cardBg: 'white',
      cardHeaderBorderColor: '#f2f2f2',
      cardTitleColor: '#434b5d',
      cardTitleTextSize: '16px',
      cardVisitClassBtnBgColor: 'white',
      cardVisitClassBtnBgHoverColor: '#00b0ff',
      cardVisitClassBtnTextColor: '#00b0ff',
      cardVisitClassBtnTextHoverColor: 'white',
      cardVisitClassBtnBorderColor: '#00b0ff',
      cardVisitClassBtnTextSize: '10px',
      cardUserInfoLabelColor: '#434b5d',
      cardUserInfoLabelTextSize: '13px',
      cardUserInfoContentColor: '#4aac8b',
      cardActiveStatusBgColor: 'rgba(0, 176, 255, 0.2)',
      cardActiveStatusTextColor: '#0083be',
      cardActiveStatusTextSize: '10px',
      cardArchiveStatusBgColor: 'rgba(0, 176, 255, 0.2)',
      cardArchiveStatusTextColor: '#0083be',
      cardArchiveStatusTextSize: '10px'
    }
  }
};
