
// questionsOrderList
export const ORDERLIST_ADD_ALT_RESPONSES = '[questionsOrderList] ORDERLIST_ADD_ALT_RESPONSES';
export const ORDERLIST_UPDATE_ALT_VALIDATION_SCORE =
  '[questionsOrderList] ORDERLIST_UPDATE_ALT_VALIDATION_SCORE';
export const ORDERLIST_UPDATE_CORRECT_VALIDATION_SCORE =
  '[questionsOrderList] ORDERLIST_UPDATE_CORRECT_VALIDATION_SCORE';
