const RECORDING_INACTIVE = 'RECORDING_INACTIVE'
const RECORDING_ACTIVE = 'RECORDING_ACTIVE'
const RECORDING_COMPLETED = 'RECORDING_COMPLETED'
const PLAY = 'PLAY'
const PAUSE = 'PAUSE'
const STOP = 'STOP'
const MIC = 'MIC'
const START = 'START'
const audioSliderTotalElementCount = 48

export {
  RECORDING_INACTIVE,
  RECORDING_ACTIVE,
  RECORDING_COMPLETED,
  PLAY,
  PAUSE,
  STOP,
  MIC,
  START,
  audioSliderTotalElementCount,
}
